# Generated by Django 4.2.1 on 2023-06-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_ConfigSeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvspots',
            name='added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cvspots',
            name='location_update',
            field=models.DateTimeField(),
        ),
    ]
